import {
  siApachegroovy,
  siAstro,
  siC,
  siClojure,
  siCmake,
  siCoffeescript,
  siCplusplus,
  siCrystal,
  siCss,
  siDart,
  siDocker,
  siElixir,
  siElm,
  siErlang,
  siFortran,
  siGnubash,
  siGo,
  siHandlebarsdotjs,
  siHaskell,
  siHtml5,
  siJavascript,
  siJulia,
  siJupyter,
  siKotlin,
  siLess,
  siLua,
  siMake,
  siMarkdown,
  siMdx,
  siNim,
  siOcaml,
  siOpenjdk,
  siPerl,
  siPhp,
  siPostgresql,
  siPython,
  siR,
  siRuby,
  siRust,
  siSass,
  siScala,
  siSharp,
  siSolidity,
  siStylus,
  siSvelte,
  siSwift,
  siTerraform,
  siTypescript,
  siV,
  siVuedotjs,
  siWebassembly,
  siZig,
} from "simple-icons";

/** GitHub's language names mapped to a logo. Anything missing falls back to initials. */
const LOGOS: Record<string, { path: string }> = {
  Astro: siAstro,
  C: siC,
  "C#": siSharp,
  "C++": siCplusplus,
  Clojure: siClojure,
  CMake: siCmake,
  CoffeeScript: siCoffeescript,
  Crystal: siCrystal,
  CSS: siCss,
  Dart: siDart,
  Dockerfile: siDocker,
  Elixir: siElixir,
  Elm: siElm,
  Erlang: siErlang,
  Fortran: siFortran,
  Go: siGo,
  Groovy: siApachegroovy,
  Handlebars: siHandlebarsdotjs,
  Haskell: siHaskell,
  HCL: siTerraform,
  HTML: siHtml5,
  Java: siOpenjdk,
  JavaScript: siJavascript,
  Julia: siJulia,
  "Jupyter Notebook": siJupyter,
  Kotlin: siKotlin,
  Less: siLess,
  Lua: siLua,
  Makefile: siMake,
  Markdown: siMarkdown,
  MDX: siMdx,
  Nim: siNim,
  OCaml: siOcaml,
  Perl: siPerl,
  PHP: siPhp,
  PLpgSQL: siPostgresql,
  Python: siPython,
  R: siR,
  Ruby: siRuby,
  Rust: siRust,
  Scala: siScala,
  SCSS: siSass,
  Shell: siGnubash,
  Solidity: siSolidity,
  Stylus: siStylus,
  Svelte: siSvelte,
  Swift: siSwift,
  TypeScript: siTypescript,
  V: siV,
  Vue: siVuedotjs,
  WebAssembly: siWebassembly,
  Zig: siZig,
};

/** SVG path (24 by 24 viewBox) for a language's logo, or null when we have none. */
export function languageLogo(name: string): string | null {
  return LOGOS[name]?.path ?? null;
}
